In [1]:
import numpy as np

In [3]:

imageData = np.array([[1,2,3],[9,5,6],[5,3,1]])

# Compare this pixel to its neighbors, starting at the top-left pixel and moving
# clockwise, and use bit operations to efficiently update the feature vector
pixel = imageData[1][1]
            
pattern = 0
pattern = pattern | (1 << 7) if pixel < imageData[0][0] else pattern
pattern = pattern | (1 << 6) if pixel < imageData[0][1] else pattern
pattern = pattern | (1 << 5) if pixel < imageData[0][2] else pattern
pattern = pattern | (1 << 4) if pixel < imageData[1][2] else pattern
pattern = pattern | (1 << 3) if pixel < imageData[2][2] else pattern
pattern = pattern | (1 << 2) if pixel < imageData[2][1] else pattern
pattern = pattern | (1 << 1) if pixel < imageData[2][0] else pattern
pattern = pattern | (1 << 0) if pixel < imageData[1][0] else pattern

print (pattern)

def print_LBP_Pattern_3x3(imageData):
    pixel = imageData[1][1]
            
    pattern = 0
    pattern = pattern | (1 << 7) if pixel < imageData[0][0] else pattern
    pattern = pattern | (1 << 6) if pixel < imageData[0][1] else pattern
    pattern = pattern | (1 << 5) if pixel < imageData[0][2] else pattern
    pattern = pattern | (1 << 4) if pixel < imageData[1][2] else pattern
    pattern = pattern | (1 << 3) if pixel < imageData[2][2] else pattern
    pattern = pattern | (1 << 2) if pixel < imageData[2][1] else pattern
    pattern = pattern | (1 << 1) if pixel < imageData[2][0] else pattern
    pattern = pattern | (1 << 0) if pixel < imageData[1][0] else pattern
    return pattern
    


17


In [7]:
# Give an example of input data that generates a LBP value of 241
imageData = np.zeros((3,3))
pattern = 241
imageData[0][0] = 1 if pattern & (1<<7) else 0
imageData[0][1] = 1 if pattern & (1<<6) else 0
imageData[0][2] = 1 if pattern & (1<<5) else 0
imageData[1][2] = 1 if pattern & (1<<4) else 0
imageData[2][2] = 1 if pattern & (1<<3) else 0
imageData[2][1] = 1 if pattern & (1<<2) else 0
imageData[2][0] = 1 if pattern & (1<<1) else 0
imageData[1][0] = 1 if pattern & (1<<0) else 0
                   
# Center - Set to zero
imageData[1][1] = 0      
print (imageData)
           
    
def printImageLBP_Pattern3x3(pattern):
    imageData = np.zeros((3,3))
    imageData[0][0] = 1 if pattern & (1<<7) else 0
    imageData[0][1] = 1 if pattern & (1<<6) else 0
    imageData[0][2] = 1 if pattern & (1<<5) else 0
    imageData[1][2] = 1 if pattern & (1<<4) else 0
    imageData[2][2] = 1 if pattern & (1<<3) else 0
    imageData[2][1] = 1 if pattern & (1<<2) else 0
    imageData[2][0] = 1 if pattern & (1<<1) else 0
    imageData[1][0] = 1 if pattern & (1<<0) else 0
                   
    # Center - Set to zero
    imageData[1][1] = 0      
    return imageData

[[ 1.  1.  1.]
 [ 1.  0.  1.]
 [ 0.  0.  0.]]


In [8]:
imageData = np.array([[1,2,3],[9,5,6],[5,3,1]])

print(print_LBP_Pattern_3x3(imageData))

print(printImageLBP_Pattern3x3(241))

17
[[ 1.  1.  1.]
 [ 1.  0.  1.]
 [ 0.  0.  0.]]
