In [1]:
import numpy as np


In [2]:
#basic
imageData = np.array([[1,3,2,1],[2,1,2,1],[1,1,1,1],[2,2,1,2]])

print(imageData)
integralData= imageData.cumsum(axis=0).cumsum(axis=1)
print (integralData)


[[1 3 2 1]
 [2 1 2 1]
 [1 1 1 1]
 [2 2 1 2]]
[[ 1  4  6  7]
 [ 3  7 11 13]
 [ 4  9 14 17]
 [ 6 13 19 24]]


In [3]:
#Access to area of boxes
class SummedAreaTable(object):
  def __init__(self, imageData):
    self.imageData = imageData 
    self.generate()  

  def getII(self, row, col):
      return self.integralData[row,col]

  def total(self, row0, col0, row1, col1):
    """
    get the cummulative value of this instance from point (row0, col0) to (row1, col1)
    """
    a = self.getII(row0 - 1, col0 - 1)
    b = self.getII(row0 - 1, col1)
    c = self.getII(row1, col0 - 1)
    d = self.getII(row1, col1)
    return d - b - c + a

  def generate(self):    
    self.integralData = self.imageData.cumsum(axis=0).cumsum(axis=1)
    
area = SummedAreaTable(imageData)  
print (area.total(1, 1, 2, 2))

5
