In [1]:
import numpy as np
import operator
import os
import cv2
import re
import pylab as pl
from fnmatch import fnmatch
from IPython.core.display import Image
import matplotlib.pyplot as plt
from PIL import Image

In [5]:
a=np.array([[0,1,1,0,2,0,0,0],
            [0,0,0,0,0,0,0,0],
            [0,0,2,3,2,0,0,0],
            [3,4,1,0,2,3,1,2],
            [0,1,2,2,0,3,1,0],
            [0,0,0,0,1,0,0,0],
            [4,0,0,1,2,0,3,1],
            [0,0,1,2,0,3,0,2]])
kernel=np.array([[0,1,0],
                 [1,0,1],
                 [0,1,0]])

In [7]:
print(a)
print("\n",kernel)

[[0 1 1 0 2 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 2 3 2 0 0 0]
 [3 4 1 0 2 3 1 2]
 [0 1 2 2 0 3 1 0]
 [0 0 0 0 1 0 0 0]
 [4 0 0 1 2 0 3 1]
 [0 0 1 2 0 3 0 2]]

 [[0 1 0]
 [1 0 1]
 [0 1 0]]


In [10]:
print(kernel[0][1])

1


In [12]:
downsample=a[::2,::2]
print(downsample)

[[0 1 2 0]
 [0 2 2 0]
 [0 2 0 1]
 [4 0 2 3]]


In [13]:
from scipy.ndimage import convolve
convolve(a, kernel)

array([[1, 2, 2, 3, 2, 2, 0, 0],
       [0, 1, 3, 3, 4, 0, 0, 0],
       [3, 6, 4, 4, 5, 5, 1, 2],
       [7, 5, 8, 8, 5, 6, 6, 3],
       [4, 6, 4, 2, 8, 4, 4, 3],
       [4, 1, 2, 4, 2, 4, 4, 1],
       [4, 4, 2, 4, 2, 8, 1, 6],
       [4, 1, 3, 4, 7, 3, 8, 5]])